#!/bin/bash

# ============================================================================
# ROAST DATABASE
# Used by roast.sh
# Categories contain arrays of roast messages
# Add new roasts freely — more chaos = better CLI experience
# Last updated - 08/04/2026
# ============================================================================

# ---------------------------------------------------------------------------
# GIT
# ---------------------------------------------------------------------------

GIT_INSULTS=(
"commit message 'fix stuff' ah? en fix madidya maga"
"git log nodu bro… full accident scene"
"force push to main ah?? ayyo HR meeting loading"
"merge conflict ah? code kooda nin jothe adjust agalla"
"ninna branches silk board signal tara tangled aagide"
"staging area nodu… market road sunday morning tara"
"rebase try madtidiya? sari guru, best of luck"
".gitignore useless da… everything tracked"
"remote track agalla? git kooda ninna trust madalla"
"ee commit next standup alli roast agutte guarantee"
"git diff nodidre two different people madidange ide"
"node_modules commit madidya? repo crying bro"
"stash madoke gothilla, direct push madidya"
"git blame full nin name… proud moment"
"3 lines change ge 47 files touched… how guru"
"branch name 'final_final_last_actual' ah?? decide bro"
"PR open madi 3 months aytu… reviewer missing"
"commit history nodu… wip wip2 wip_final ayyo"
"detached HEAD state… nin mind tara floating"
"merge to main without review ah? bold maga"
"tag maadoke gothilla? version management RIP"
"submodule add madidya? life already complicated bro"
"git clean -fd run madidya? files bye bye"
"conflict resolve madtidya athava guess madtidya?"
"bro git reset --hard production alli run madbeda please"
"commit message 'small change' ah? diff 900 lines ide bro"
"git status nodi silent agidya? yeah same feeling"
"branch create madtidya daily delete madalla repo forest aagide"
"git push reject aaytu? remote kooda reject madide nin work"
"git stash madtidya but restore madalla forgotten forever"
"merge madidya athava pray madidya?"
"git log nodidre archaeology dig site tara ide"
"commit time 3:17am… debugging trauma visible"
"git add . madtidya blindly every time"
"PR description empty… confidence full"
"branch naming random numbers bro"
"git config email wrong repo history ruined"
"repo size nodu… node_modules museum"
"git pull madidya conflict surprise loading"
"force push madidya team Slack silent"
"commit message emoji only?? documentation RIP"
"git blame nodidre whole file nin hesaru"
"branch rebasing madtidya athava guessing?"
"git cherry pick madtidya commit dependency gothilla"
"submodule add madidya why guru why"
"git revert madbekittu reset madidya"
"stash stack nodu bro forgotten memories"
"PR open madi 6 months aytu fossil"
"merge commit message auto default leave madidya"
"git tag missing release panic"
"git checkout wrong branch production scare"
"git history rewrite madtidya archaeologist"
"commit madoke marethiya half day work"
"git clean run madidya now files gone"
"repo clone time 15 mins ayyo"
)

# ---------------------------------------------------------------------------
# PYTHON
# ---------------------------------------------------------------------------

PYTHON_INSULTS=(
"indentation error again ah? spaces vs tabs war still on"
"ImportError ah? package install madoke marethiya"
"list comprehension gothilla? loop life forever"
"SyntaxError bro… python kooda confuse agide"
"venv broke ah? entire project haunted now"
"bugs nodu… PG bedbugs tara everywhere"
"try except illa? bold strategy guru"
"infinite loop ah… code stuck life stuck"
"pip install madoke gothilla aa?"
"script speed nodu… ORR traffic 6pm"
"global variable everywhere… architecture RIP"
"except Exception pass ah? debugging cancelled"
"print debug madtidiya still? pdb gothilla?"
"requirements.txt illa… project run agalla"
"f-string gothilla still % formatting ah?"
"function 200 lines ide… break madappa"
"type hints illa comments illa… mystery novel"
"circular import ah… modules fight madtide"
"password hardcode madidya? security crying"
"recursive function base case illa… stack overflow coming"
"lambda function overuse madidya… calm down bro"
"pandas run madoke 20 mins… crash last line"
"conda pip mix madidya… environment gone"
"walrus operator random place alli use madidya why"
"python script ge 4GB RAM beku anta ide"
"python script run madidya output empty bro"
"variable name temp_final2_final genius level"
"for loop inside 4 loops performance RIP"
"dictionary key typo ge 30 min debug"
"file name script_new_final_last.py"
"time.sleep add madidya fix anta"
"import * madidya namespace explosion"
"unused variable collection museum"
"script run madoke 7 arguments documentation illa"
"list index error classic python moment"
"python version mismatch surprise"
"json parse fail comma missing"
"indentation fix madoke 4 attempts"
"print debug festival running"
"pandas dataframe shape nodidya atleast"
"script run madidya nothing happening"
"try except elli crash guaranteed"
"lambda readability destroy madide"
"random import unused everywhere"
"config hardcoded everywhere"
"function return madalla always None"
"global variable dependency web"
"recursive call infinite"
"script CPU melt madtide"
"numpy array dimension confusion"
"pandas merge wrong key disaster"
"exception swallow madidya debugging RIP"
"string concat loop alli slow motion"
"dict access keyerror surprise"
"python interpreter sigh madide"
)

# ---------------------------------------------------------------------------
# LINUX / SYSTEM
# ---------------------------------------------------------------------------

LINUX_INSULTS=(
"permission denied… system itself scared of you"
"command died instantly bro"
"shell script nodu… full holes"
"rm -rf madtidya casually? resume ready aa?"
"systemd service start agalla… classic"
"kernel panic ah… ayyo"
"filesystem messy guru"
"random command type madtidya guess madoke"
"cron job run agalla… schedule RIP"
"chmod 777 ah? security bye bye"
"sudo rm run madoke munche swalpa read maadu"
"disk full… /var/log nodu"
"alias rm ge rm -rf madidya? dangerous bro"
"swap full agide… RAM tired"
".bashrc break madidya… terminal open agalla"
"sed wrong run madidya… file single line"
"awk try madtidya… python use maadu bro"
"pipe chain 8 commands… yaavudu fail gothilla"
"nohup illa background process gone"
"dd wrong disk target madidya? ayyo"
"grep -r / run madtidya… patience ide ninige"
"top nodu… nin process 99% CPU"
"ulimit hit agide… too many files open"
"journal logs nodidya last week atleast?"
"cd wrong folder again guru"
"ls nodidre 5000 files ayyo"
"rm wrong file backup illa"
"chmod number guess madtidya?"
"systemctl restart everything approach"
"grep wrong directory search madtidya"
"sudo habit ge use madtidya"
"env variable typo ge 2 hours debug"
"PATH break madidya terminal crying"
"script execute permission illa"
"/tmp full disk panic"
"journalctl nodoke marethiya"
"process kill guess madtidya"
"screen session lost again"
"tmux window disappear aytu"
"mount point confusion festival"
"service running nothing working"
"log file 4GB ide nodidya"
"swap usage scary bro"
"shell script debug nightmare"
"alias break madidya command"
"cron syntax wrong silent failure"
"nohup marethiya process gone"
"ulimit hit file open panic"
"tar flags confuse again"
"sed wrong replace disaster"
"awk script readability zero"
"pipe chain mystery failure"
"system load 20 ayyo"
"kernel log scary reading"
)

# ---------------------------------------------------------------------------
# NETWORK
# ---------------------------------------------------------------------------

NETWORK_INSULTS=(
"connection refused… server mood illa"
"SSH key trust madalla nin mele"
"DNS fail… google kooda confuse"
"packet loss silk board traffic tara"
"firewall rules full confusion bro"
"timeout agide… rapido kooda faster"
"bandwidth zero… nothing moving"
"SSL handshake fail… https reject madide"
"proxy settings whitefield road tara"
"ping madtidya localhost ge internet check ge??"
"port already in use… who knows which process"
"curl without -L run madtidya… redirect nodu"
"wrong server SSH madidya again?"
"firewall port open madoke marethiya"
"certificate expired… users calling now"
"hardcoded IP address classic move"
"API call timeout illa… thread hanging"
"CORS error nodu… backend angry"
"VPN on madoke marethiya internal API ge"
"load balancer health check crying"
"ping wrong host ge madtidya"
"dns cache flush gothilla aa"
"ip typo ge full debug"
"localhost vs ip confusion"
"curl wrong port hit madtidya"
"server up service dead"
"telnet try madidya atleast"
"api endpoint wrong path"
"timeout value unrealistic"
"network blame default option"
"router reboot classic fix"
"vpn off internal access try"
"http https confusion"
"port number guess game"
"connection drop mystery"
"certificate chain broken"
"load test accidentally run"
"dns propagation wait marethiya"
"network log nodidya"
"bandwidth eaten ghost"
"proxy config broken"
"tcp handshake fail story"
"firewall silent block"
"route table wrong entry"
"ssl verify fail ayyo"
"api rate limit hit"
"latency high patience low"
"packet drop festival"
"traceroute nowhere reach"
"socket timeout endless wait"
)

# ---------------------------------------------------------------------------
# GENERIC / MISC
# ---------------------------------------------------------------------------

GENERIC_INSULTS=(
"this failed hard bro"
"errors everywhere nodu"
"stack trace novel size ide"
"bug stubborn guru"
"logic alli holes ide"
"segfault ah… ayyo"
"not bug feature anta helbeda please"
"debugger ninna life question madtide"
"error count only increasing"
"sarjapur traffic speed idu"
"same command 4 times run madtidya"
"stackoverflow copy paste ah?"
"worked on your machine ah? production ge send your laptop"
"silent wrong output worst bug"
"fix comment out madidya instead bug"
"TODO from 2019 still ide"
"magic number random calculation alli"
"variable name data_final_final2 ah?"
"400 line function… congrats"
"production hotfix testing illa"
"regex bareediya ninige kooda gothilla"
"3 hours debug 2 second fix"
"off by one error classic"
"race condition only production alli"
"memory leak slow death"
"unit test illa CI pass because nothing exists"
"bug fix madoke new bug add madidya"
"logic hole full swiss cheese"
"code compile agalla obvious reason"
"run madidya result nonsense"
"documentation empty file classic"
"comments outdated since 2020"
"debugging patience test running"
"console.log festival ide"
"code readability missing entirely"
"variable reuse madness"
"refactor anta heltidya worse agide"
"test fail ignore madtidya"
"error message read madidya atleast"
"IDE warnings ignore madtidya"
"commit before testing classic move"
"config mismatch surprise"
"dependency version chaos"
"feature break unknowingly"
"edge case kill madide"
"production surprise moment"
"stack trace scroll marathon"
"code review skip madtidya"
"unit test missing again"
"magic numbers everywhere"
"silent failure worst bug"
"null pointer vibe"
"data mismatch confusion"
"state management collapse"
"performance degrade slowly"
"debugger crying inside"
)

# ---------------------------------------------------------------------------
# UNKNOWN COMMAND
# ---------------------------------------------------------------------------

UNKNOWN_CMD_INSULTS=(
"en guru idu command aa?"
"keyboard mele kai slip ayta?"
"google kooda gothilla ee command"
"idenu language bro"
"cat keyboard mele nadita?"
"new programming language invent madtidya?"
"swalpa think madi type maadu"
"bash kooda confused ide"
"confidence ide but command illa"
"this is not command bro"
"autocomplete kooda give up madide"
"open new terminal pretend nothing happened"
"3 typos one command record"
"which keyboard bro asking seriously"
"fingers keyboard jothe fight madtide"
"history alli idu save agutte shame"
"bash answer kodoke time togondide"
"idenu random letters guru"
"terminal shock aytu"
"bash think madtide response ge"
"autocomplete crying quietly"
"keyboard slip ayta bro"
"command spelling missing"
"syntax missing everything"
"terminal asking help"
"command structure collapse"
"shell history embarrassed"
"fish shell kooda reject madutte"
"command interpretation impossible"
"bash parser panic"
"keyboard smash detected"
"error message confused"
"shell language mismatch"
"command ghost ide"
"unknown command legend"
"syntax disaster"
"try again calmly bro"
"bash confused silence"
"man page kooda exist illa"
"autocomplete resign madide"
"command hallucination"
"terminal patience test"
)

# ---------------------------------------------------------------------------
# DESI RANDOM EXTRAS
# ---------------------------------------------------------------------------

DESI_EXTRAS=(
"ayyo guru"
"sari illa bro"
"swalpa calm agi try maadu"
"coffee kudkondu baa"
"deep breath bro"
"yeno madtidya explain"
"standup alli idu mention agutte"
"manager nodidre problem"
"production ge idu hogbeda please"
"repo crying right now"
"server kooda tired"
"system asking why"
"life choices rethink maadu"
"terminal ge break beku"
"keyboard rest ge hogbeku"
"debug madappa"
"ayyo paapa"
"maga swalpa slow maadu"
"bro relax first"
"coffee break time"
"production ge idu hogalla"
"team chat silent agutte"
"manager nodtare careful"
"repo crying bro"
"server sweating"
"terminal patience test"
"deep breath guru"
"restart brain once"
"sleep deprivation visible"
"keyboard tired ide"
"debug madappa please"
"ayyo ayyo"
"office roast loading"
"tea break hogona"
"standup alli idu barutte"
"weekend deploy madbeda"
)

# ---------------------------------------------------------------------------
# UNKNOWN EXTRA LINES
# ---------------------------------------------------------------------------

UNKNOWN_EXTRAS=(
"swalpa google maadu next time"
"man page try madidya?"
"confidence ide logic illa"
"terminal asking what bro"
"keyboard smash madbeda"
"sleep madkondu baa"
)
