.TH ROAST-STATS 1 "April 2026" "elite-roast 1.0" "User Commands"
.SH NAME
roast-stats \- show elite-roast failure count for today
.SH SYNOPSIS
.B roast-stats
.SH DESCRIPTION
Displays the number of failed or unknown commands recorded by elite-roast
in the current session day.
.SH AUTHOR
Nishanth C <nishanthc264@gmail.com>
.SH SEE ALSO
bash(1)
